/*
 * Copyright (C) 2013, 2014 beamproject.org
 *
 * This file is part of beam-client.
 *
 * beam-client is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * beam-client is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.beamproject.client.ui;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author René Bernhardsgrütter <rene.bernhardsgruetter@gmail.com>
 */
public class AboutWindow extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private final int ESCAPE_KEY_CODE = 27;
    private final String WEBSITE_URL = "https://www.beamproject.org/";
    private final String BACKGROUND_IMAGE_PATH = "/org/beamproject/client/ui/aboutWindowBackground.png";
    private final float FRAME_BORDER_RADIUS_IN_PX = 15f;

    /**
     * Creates new form AboutWindow
     */
    public AboutWindow() {
        initComponents();
        setLocationRelativeTo(null);
        configureRoundedCorner();
        setVersion();
    }

    private void configureRoundedCorner() {
        Graphics2D g2d = (Graphics2D) getGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON));
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        RoundRectangle2D shape = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), FRAME_BORDER_RADIUS_IN_PX, FRAME_BORDER_RADIUS_IN_PX);
        setShape(shape);
    }

    /**
     * This method is special since Maven updates this code automatically during
     * compilation. Do not change the text, the formatting or anything else
     * without checking the pom.xml and testing the version update manually in
     * the AboutWindow!
     */
    private void setVersion() {
        final String POM_VERSION = "0.0.1"; // This will be updated by Maven - DO NOT CHANGE!
        versionLabel.setText("Version " + POM_VERSION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel =  new javax.swing.JPanel() {
            private static final long serialVersionUID = 1L;

            @Override
            public void paintComponent(Graphics g) {
                ImageIcon imageicon = new ImageIcon(getClass().getResource(BACKGROUND_IMAGE_PATH));
                Image image = imageicon.getImage();

                super.paintComponent(g);

                if (image != null) {
                    g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        contentPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        thankYouLabel = new javax.swing.JLabel();
        introLabel = new javax.swing.JLabel();
        helpUsLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        linkLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        backgroundPanel.setPreferredSize(new java.awt.Dimension(550, 330));

        contentPanel.setOpaque(false);
        contentPanel.setPreferredSize(new java.awt.Dimension(526, 318));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/beamproject/client/ui/aboutWindowLogo.png"))); // NOI18N
        logoLabel.setText("                      ");

        thankYouLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        thankYouLabel.setForeground(new java.awt.Color(254, 254, 254));
        thankYouLabel.setText("<html>Thank you for using Beam!</html>");

        introLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        introLabel.setForeground(new java.awt.Color(254, 254, 254));
        introLabel.setText("<html><b>Beam</b> – a userfiendly messenger.<br />Open Source, independent, anonymous and uniquely secure.</html>");

        helpUsLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        helpUsLabel.setForeground(new java.awt.Color(254, 254, 254));
        helpUsLabel.setText("<html>Help us to make Beam better and contribute code, spend us a beer or run a Beam server. The latter is surprisingly easy! Visit beamproject.org to learn more.</html>");

        versionLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(175, 175, 175));
        versionLabel.setText("Version");
        versionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        copyrightLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        copyrightLabel.setText("<html>This software was developed by the team behind beamproject.org and released under the terms of the GPLv3 or later. © 2014 beamproject.org.</html>");
        copyrightLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        linkLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        linkLabel.setForeground(new java.awt.Color(2, 2, 122));
        linkLabel.setText("www.beamproject.org");
        linkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(introLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(helpUsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(copyrightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(versionLabel))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(thankYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(linkLabel)))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(introLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpUsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thankYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(versionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyrightLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        dispose();
    }//GEN-LAST:event_formMouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if (evt.getKeyCode() == ESCAPE_KEY_CODE) {
            dispose();
        }
    }//GEN-LAST:event_formKeyTyped

    private void linkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMouseClicked
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URL(WEBSITE_URL).toURI());
                dispose();
                return;
            } catch (IOException | URISyntaxException ex) {
                Logger.getLogger(AboutWindow.class.getSimpleName()).log(Level.WARNING, "Could not open the website ''" + WEBSITE_URL + "'' since: {0}", ex.getMessage());
            }
        }

        try {
            ProcessBuilder processBuilder = new ProcessBuilder("x-www-browser", WEBSITE_URL);
            processBuilder.start();
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(AboutWindow.class.getName()).log(Level.WARNING, "Could not open the website ''" + WEBSITE_URL + "'' since: {0}", ex.getMessage());
        }
    }//GEN-LAST:event_linkLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel helpUsLabel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel thankYouLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
