/*
 * Copyright (C) 2013, 2014 inchat.org
 *
 * This file is part of inchat-client.
 *
 * inchat-client is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * inchat-client is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.inchat.client.ui;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author René Bernhardsgrütter <rene.bernhardsgruetter@gmail.com>
 */
public class AboutWindow extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private final int ESCAPE_KEY_CODE = 27;
    private final String WEBSITE_URL = "https://www.inchat.org/";
    private final String POM_VERSION = "0.0.1"; // This will be updated by Maven
    private final String BACKGROUND_IMAGE_PATH = "/org/inchat/client/ui/aboutWindowBackground.png";
    private final float FRAME_BORDER_RADIUS_IN_PX = 15f;

    /**
     * Creates new form AboutWindow
     */
    public AboutWindow() {
        initComponents();
        setLocationRelativeTo(null);
        configureRoundedCorner();
        setVersion();
    }

    private void configureRoundedCorner() {
        Graphics2D g2d = (Graphics2D) getGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON));
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        RoundRectangle2D shape = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), FRAME_BORDER_RADIUS_IN_PX, FRAME_BORDER_RADIUS_IN_PX);
        setShape(shape);
    }
    
    private void setVersion() {
        versionLabel.setText("Version " + POM_VERSION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel =  new javax.swing.JPanel() {
            private static final long serialVersionUID = 1L;

            @Override
            public void paintComponent(Graphics g) {
                ImageIcon imageicon = new ImageIcon(getClass().getResource(BACKGROUND_IMAGE_PATH));
                Image image = imageicon.getImage();

                super.paintComponent(g);

                if (image != null) {
                    g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        contentPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        thankYouLabel = new javax.swing.JLabel();
        introLabel = new javax.swing.JLabel();
        helpUsLabel = new javax.swing.JLabel();
        websiteButton = new javax.swing.JButton();
        copyrightLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 330));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        contentPanel.setOpaque(false);

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inchat/client/ui/aboutWindowLogo.png"))); // NOI18N
        logoLabel.setText("                      ");

        thankYouLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        thankYouLabel.setForeground(new java.awt.Color(254, 254, 254));
        thankYouLabel.setText("<html>Thank you for using inchat!</html>");

        introLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        introLabel.setForeground(new java.awt.Color(254, 254, 254));
        introLabel.setText("<html><b>inchat</b> – a userfiendly messenger.<br />Open Source, independent, anonymous and uniquely secure.</html>");

        helpUsLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        helpUsLabel.setForeground(new java.awt.Color(254, 254, 254));
        helpUsLabel.setText("<html>Help us to make inchat better and contribute code, spend us a beer or run an inchat server. The latter is surprisingly easy! Visit inchat.org to learn more.</html>");

        websiteButton.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        websiteButton.setForeground(new java.awt.Color(254, 254, 254));
        websiteButton.setText("inchat.org");
        websiteButton.setBorderPainted(false);
        websiteButton.setMargin(new java.awt.Insets(0, 5, 0, 5));
        websiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteButtonActionPerformed(evt);
            }
        });

        copyrightLabel.setForeground(new java.awt.Color(175, 175, 175));
        copyrightLabel.setText("<html>This software was developed by the team behind inchat.org and released under the terms of the GPLv3 or later. © 2014 inchat.org.</html>");

        versionLabel.setForeground(new java.awt.Color(175, 175, 175));
        versionLabel.setText("Version");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyrightLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(introLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(helpUsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(thankYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(websiteButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(versionLabel)))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(introLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpUsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteButton)
                    .addComponent(thankYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        dispose();
    }//GEN-LAST:event_formMouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if (evt.getKeyCode() == ESCAPE_KEY_CODE) {
            dispose();
        }
    }//GEN-LAST:event_formKeyTyped

    private void websiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteButtonActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URL(WEBSITE_URL).toURI());
                dispose();
                return;
            } catch (IOException | URISyntaxException ex) {
                Logger.getLogger(AboutWindow.class.getSimpleName()).log(Level.WARNING, "Could not open the website ''" + WEBSITE_URL + "'' since: {0}", ex.getMessage());
            }
        }

        try {
            ProcessBuilder processBuilder = new ProcessBuilder("x-www-browser", WEBSITE_URL);
            processBuilder.start();
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(AboutWindow.class.getName()).log(Level.WARNING, "Could not open the website ''" + WEBSITE_URL + "'' since: {0}", ex.getMessage());
        }
    }//GEN-LAST:event_websiteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel helpUsLabel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel thankYouLabel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JButton websiteButton;
    // End of variables declaration//GEN-END:variables
}
